apiVersion: v1
kind: Service
metadata:
  name: honeypot-service
  namespace: cyber-lab-004
spec:
  selector:
    app: cowrie-honeypot
  type: ClusterIP
  ports:
    - name: ssh
      port: 2222
      targetPort: 2222
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowrie-deployment
  namespace: cyber-lab-004
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cowrie-honeypot
  template:
    metadata:
      labels:
        app: cowrie-honeypot
    spec:
      volumes:
      - name: shared-suricata-logs
        emptyDir: {}
      - name: log-forwarder-script
        configMap:
          name: log-forwarder-config
          defaultMode: 0777

      containers:
      # COWRIE
      - name: cowrie-container
        image: cowrie/cowrie:latest
        ports:
        - containerPort: 2222

      # SURICATA
      - name: suricata-sidecar
        image: jasonish/suricata:latest
        securityContext:
          privileged: true
        command: ["/bin/sh", "-c"]
        args:
          - suricata-update && suricata -i eth0 --af-packet=eth0 -l /suricata-logs
        volumeMounts:
        - name: shared-suricata-logs
          mountPath: /suricata-logs

      # A BALSA DE AÇO
      - name: log-forwarder-sidecar
        image: alpine:latest
        command: ["/scripts/forwarder.sh"]
        volumeMounts:
        # A CAIXA DE ENTREGA AGORA PODE SER ESCRITA E LIDA
        - name: shared-suricata-logs
          mountPath: /suricata-logs
        - name: log-forwarder-script
          mountPath: /scripts
