apiVersion: v1
kind: ConfigMap
metadata:
  name: log-forwarder-config
  namespace: cyber-lab-004
data:
  # O nome do arquivo de script
  forwarder.sh: |
    #!/bin/sh
    
    # --- A PORRA DA CAIXA-PRETA ---
    # Redireciona TODA a saída (stdout e stderr) deste script para um arquivo de debug
    # A gente vai escrever na MESMA pasta que o Suricata, porque a gente SABE que tem permissão de escrita lá.
    exec > /suricata-logs/forwarder-debug.log 2>&1
    
    # Liga o modo "fofoqueiro". Cada comando executado será impresso no log.
    set -x

    echo "--- SCRIPT DA CAIXA-PRETA INICIADO ---"
    
    apk add --no-cache curl tail
    
    LOG_FILE="/suricata-logs/eve.json"
    LOKI_URL="http://loki-service:3100/loki/api/v1/push"

    echo "Esperando por $LOG_FILE..."
    while [ ! -f "$LOG_FILE" ]; do
      sleep 2
    done
    echo "Arquivo encontrado. Começando a seguir..."
    
    tail -F "$LOG_FILE" | while read -r line; do
      echo "Linha lida do Suricata."
      ESCAPED_LINE=$(echo "$line" | sed 's/"/\\"/g');
      
      echo "Enviando linha para o Loki..."
      # O curl que a gente SABE que funciona, com -v para ser fofoqueiro também
      curl -v -H "Content-Type: application/json" -XPOST -s "$LOKI_URL" --data-raw \
      "{\"streams\": [{ \"stream\": { \"job\": \"suricata\" }, \"values\": [ [ \"$(date +%sN)\", \"$ESCAPED_LINE\" ] ] }]}";
      echo "Envio concluído. Esperando próxima linha."
    done
