apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fluent-bit-egress-policy
  namespace: cyber-lab-004
spec:
  # 1. Aplique esta política ao Fluent Bit
  podSelector:
    matchLabels:
      app: fluent-bit
  
  # 2. Controle o tráfego de SAÍDA
  policyTypes:
    - Egress

  # 3. Regras de SAÍDA
  egress:
    # REGRA A: Permita falar com o Loki
    - to:
      - podSelector:
          matchLabels:
            app: loki
      ports:
        - protocol: TCP
          port: 3100
    
    # REGRA B: Permita falar com o DNS do Kubernetes
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
        podSelector:
          matchLabels:
            k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
