# --- Permissões para o Fluent Bit ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit-sa
  namespace: cyber-lab-004
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-cr
rules:
- apiGroups: [""]
  resources: [pods, namespaces]
  verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-crb
subjects:
- kind: ServiceAccount
  name: fluent-bit-sa
  namespace: cyber-lab-004
roleRef:
  kind: ClusterRole
  name: fluent-bit-cr
  apiGroup: rbac.authorization.k8s.io
---
# --- A PORRA DA CONFIGURAÇÃO FINAL E CORRETA ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: cyber-lab-004
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Daemon        Off
        Log_Level     info

    [INPUT]
        Name          tail
        Path          /var/log/containers/*.log
        Parser        docker
        Tag           kube.*
        Refresh_Interval 5
        DB            /var/log/flb_kube.db
        Inotify_Watcher false

    [FILTER]
        Name          kubernetes
        Match         kube.*
        Kube_URL      https://kubernetes.default.svc:443

    [OUTPUT]
        Name          loki
        Match         *
        Host          loki-service
        Port          3100
        Labels        job=fluent-bit, namespace=$kubernetes['namespace_name'], pod=$kubernetes['pod_name'], container=$kubernetes['container_name']
---
# --- O DAEMONSET (COMPLETO E CORRETO) ---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit-daemonset
  namespace: cyber-lab-004
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      serviceAccountName: fluent-bit-sa
      volumes:
      - name: fluent-bit-config-volume
        configMap:
          name: fluent-bit-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      containers:
      - name: fluent-bit-container
        image: fluent/fluent-bit:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        args:
        - "-c"
        - "/fluent-bit/etc/fluent-bit.conf"
        volumeMounts:
        - name: fluent-bit-config-volume
          mountPath: /fluent-bit/etc
        - name: varlog
          mountPath: /var/log
          # readOnly: true  <-- A PORRA DO CÂNCER FOI REMOVIDA DAQUI
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
