# --- O Pedido de Armazenamento para o Grafana ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: cyber-lab-004
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # 1GB é mais que suficiente para dashboards
---
# --- O Service: O endereço para acessar a interface web do Grafana ---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: cyber-lab-004
spec:
  type: NodePort # Expõe o serviço para fora do cluster
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000      # A porta interna do Grafana
      targetPort: 3000 # A porta onde o container escuta
---
# --- O Deployment: Garante que o Grafana esteja sempre rodando ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: cyber-lab-004
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-pvc
      containers:
      - name: grafana-container
        image: grafana/grafana:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        # Montamos o "HD virtual" na pasta onde o Grafana guarda seus dados
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
