# As permissões RBAC continuam as mesmas
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail-sa
  namespace: cyber-lab-004
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail-cr
rules:
- apiGroups: [""]
  resources: [nodes, nodes/proxy, services, endpoints, pods]
  verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail-crb
subjects:
- kind: ServiceAccount
  name: promtail-sa
  namespace: cyber-lab-004
roleRef:
  kind: ClusterRole
  name: promtail-cr
  apiGroup: rbac.authorization.k8s.io
---
# O CONFIGMAP INTELIGENTE (ASPIRADOR DE PÓ)
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: cyber-lab-004
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://loki-service:3100/loki/api/v1/push
    scrape_configs:
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
      - role: pod
      pipeline_stages:
      - docker: {}
      relabel_configs:
      - source_labels: ['__meta_kubernetes_pod_label_app']
        target_label: 'app'
---
# O DAEMONSET COM A CHAVE MESTRA
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail-daemonset
  namespace: cyber-lab-004
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail-sa
      # DAMOS A ELE ACESSO A TODAS AS PASTAS DE LOG RELEVANTES
      volumes:
      - name: promtail-config-volume
        configMap:
          name: promtail-config
      - name: pods-logs
        hostPath:
          path: /var/log/pods
      - name: containers-logs
        hostPath:
          path: /var/log/containers
      - name: docker-logs
        hostPath:
          path: /var/lib/docker/containers

      containers:
      - name: promtail-container
        image: grafana/promtail:latest
        imagePullPolicy: IfNotPresent
        args:
        - "-config.file=/etc/promtail/promtail.yaml"
        securityContext:
          privileged: true # A chave mestra
        volumeMounts:
        - name: promtail-config-volume
          mountPath: /etc/promtail
        - name: pods-logs
          mountPath: /var/log/pods
          readOnly: true
        - name: containers-logs
          mountPath: /var/log/containers
          readOnly: true
        - name: docker-logs
          mountPath: /var/lib/docker/containers
          readOnly: true
